# Generated by Django 5.1 on 2024-11-02 09:54

import usercradintials.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=40)),
                ('Phone_Number', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20, validators=[usercradintials.models.validate_password_strength])),
                ('confirmPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
