# Generated by Django 5.1 on 2024-11-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_expensesregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesregister',
            name='type',
            field=models.CharField(choices=[('one_time', 'one_time'), ('monthly', 'monthly'), ('Quarterly', 'Quarterly'), ('Halfyealy', 'Halfyealy'), ('Yearly', 'Yearly')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
