# Generated by Django 5.1 on 2024-11-09 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incomes', '0002_alter_incomesource_date'),
        ('usercradintials', '0003_userdetails_created_at_userdetails_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercradintials.userdetails')),
            ],
        ),
    ]
