# Generated by Django 5.1 on 2024-11-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incomes', '0004_alter_incomesource_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomesource',
            name='date',
            field=models.DateField(),
        ),
    ]
