# Generated by Django 5.1 on 2024-11-12 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budgets', '0001_initial'),
        ('usercradintials', '0003_userdetails_created_at_userdetails_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercradintials.userdetails')),
            ],
        ),
    ]
